name: Deploy code to GCP
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'

    - name: 'Authenticate with GCP'
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'home-monitor-373013'
        workload_identity_provider: 'projects/345305797254/locations/global/workloadIdentityPools/github/providers/cuteornot'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      
    - name: 'Describe Cloud Run Instances'
      run: |
        gcloud run services describe aggregatehometotals --project="home-monitor-373013" --region="europe-west1"
